/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef DIVEL_CODIGO_ZANFA_PRIVATE_H
#define DIVEL_CODIGO_ZANFA_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.3.1.53"
#define VER_MAJOR	1
#define VER_MINOR	3
#define VER_RELEASE	1
#define VER_BUILD	53
#define COMPANY_NAME	"Divel"
#define FILE_VERSION	"1.3.1"
#define FILE_DESCRIPTION	"Decodificador de C. Zanfa"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Copyright 2011-2012"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Codigo Zanfa"
#define PRODUCT_NAME	"Divel Codigo Zanfa"
#define PRODUCT_VERSION	"Solo decodificacion"

#endif /*DIVEL_CODIGO_ZANFA_PRIVATE_H*/
