/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef DIVEL_CAJAS_PRIVATE_H
#define DIVEL_CAJAS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.6"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	6
#define COMPANY_NAME	"Divel"
#define FILE_VERSION	"0.1.1"
#define FILE_DESCRIPTION	"Suite matemática Pitágoras"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"(C) Adrian Arroyo Calle 2011 /Revision 2012"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Divel Cajas"
#define PRODUCT_VERSION	"1.0.0"

#endif /*DIVEL_CAJAS_PRIVATE_H*/
