/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef FRACCIONADOR_PRIVATE_H
#define FRACCIONADOR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.1.3"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	3
#define COMPANY_NAME	"Divel"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Detector de fracciones (valor decimal, propia,...)"
#define INTERNAL_NAME	"fracc.exe"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Fraccioneitor"
#define PRODUCT_NAME	"Fraccionador"
#define PRODUCT_VERSION	"Versión Superior de Fraccioneitor"

#endif /*FRACCIONADOR_PRIVATE_H*/
