#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "Zanfa.h"
//Programa original 2011-Revisión veraniega 2012
/*
*************************************************
**Divel Código Zanfa -- 2011*********************
*************************************************
**Revision 2012 -- 2012 11/08/12 17:29
*************************
*************************************************
**(C) Adrián Arroyo Calle para Divel 2011-2012***
*************************************************
**Fin de soporte: Enero-2013*********************
*************************************************
*/

int main(int argc, char *argv[])
{
    int a,opr,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;
  printf("Bienvenido al asistente de decoficicacion de Divel para Codigo Zanfa\n");
  printf("(C)Adrian Arroyo Calle para Divel 2011-2012\n");
  printf("--------------------------------------------------------------------\n");
  printf("Menu:\n");
  printf("1. Decodificar codigo\n");
  printf("2. Codificar mensaje\n");
  printf("3. Manual de usuario\n");
  printf("---------------------Introduzca su opcion---------------------------\n");
  scanf("%d",&a);
  if (a==5){
            printf("Introduzca contrasena\n");
            scanf("%d",&n);
            if (n==0000){
                                printf("Librerias presentes: stdio.h, stdlib.h, math.h,Zanfa.h\n");
                                printf("Para observar Zanfa.h debes pedir permiso a Divel y/o Divel Media\n");
                                }
                                }
  if (a==4){
            printf("OPCIONES DE PROGRAMA TODAVIA NO OPERATIVAS EN ESTA VERSION\n");
            }
  if (a==3){
            printf("MANUAL DE USUARIO\n");
            printf("Guia de funcionamiento por opciones:\n");
            printf("1. Decodificar codigo. Nos aparecera un texto pidiendonos los numeros. Hay espacio para 10 datos, si su frase no dispone de 10 datos, no pulse ENTER hasta el infinito, usted debe de rellenar los huecos restantes con 0, pues así el programa sabe que el usuario no dispone de numero para esa palabra\n");
            printf("2. Codificar mensaje. Introduciremos el mensaje de manera que quede, palabra, ENTER, palabra, ENTER. Si no se dispone de suficientes palabras introduzca 0, nunca siga pulsando ENTER.\n");
            printf("3. Manual de Usuario que esta leyendo usted mismo\n");
            printf("4. Opciones. Zona BETA, puede estar o no estar disponible en su version.\n");
            printf("5. Lista completa de librerías y sus codigos, acceso protegido con contrasena. Si desea entrar pongase en contacto con Divel y/o Divel Media.\n");
            getchar();
            getchar();
            }
  if (a==SER){
  printf("--------------Decodificacion de codigos Zanfa-----------------------\n");
  printf("Introduce los datos separados por ENTER(max. 10):\n");
  scanf("%d",&opr);
  scanf("%d",&b);
  scanf("%d",&c);
  scanf("%d",&d);
  scanf("%d",&e);
  scanf("%d",&f);
  scanf("%d",&g);
  scanf("%d",&h);
  scanf("%d",&i);
  scanf("%d",&j);
  printf("DDDDDDDDD    III  VV                    VV  EEEEEEEEEEE    LLL\n");
  printf("DDD     DD   III   VV                  VV   EEEEEEEEEEE    LLL\n");
  printf("DDD      DD  III    VV                VV    EEE            LLL\n");
  printf("DDD      DD  III     VV              VV     EEE            LLL\n");
  printf("DDD      DD  III      VV            VV      EEEEEEE        LLL\n");
  printf("DDD      DD  III       VV          VV       EEEEEEE        LLL\n");
  printf("DDD      DD  III        VV        VV        EEE            LLL\n");
  printf("DDD      DD  III         VV      VV         EEE            LLL\n");
  printf("DDD     DD   III          VVVVVVVV          EEEEEEEEEEE    LLLLLLLLLLL\n");
  printf("DDDDDDDDD    III           VVVVVV           EEEEEEEEEEE    LLLLLLLLLLL\n");
  printf("\n");
  printf("Espere mientras Divel procesa los datos...\n");
  printf("\n");
  switch(opr){
              case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 :{
                        printf("INFONUMERO\n");
                        printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
                        }
              break;
              case 72 :{
                        printf("INFOPROGRAMA\n");
                        printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
                        }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              
              
              
              
              }
  switch(b){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 :{
                        printf("INFONUMERO\n");
                        printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
                        }      
              break;
              case 72 :{
                        printf("INFOPROGRAMA\n");
                        printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
                        }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              } 
  
  switch(c){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 :{ 
                        printf("INFONUMERO\n");
                        printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
                        }             
              break;
              case 72 : {
                         printf("INFOPROGRAMA\n");
                         printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
                         }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(d){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(e){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
               printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
               }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(f){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n\nRevision del ano 2012 para implemetar soporte a fallos.\nFin de soporte tecnico: Enero-2013");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(g){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(h){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(i){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  switch(j){
            case 0 : printf("\n");
              break;
              case 1 : printf("Mensaje resultante: SER\n");
              break;
              case 2 : printf("Mensaje resultante: VIVIR\n");
              break;
              case 3 : printf("Mensaje resultante: HABLAR\n");
              break;
              case 4 : printf("Mensaje resultante: PENSAR \n");
              break;
              case 5 : printf("Mensaje resultante: NECESITAR\n");
              break;
              case 45 : printf("Mensaje resultante: ORDENADOR\n");
              break;
              case 99 : printf("Mensaje resultante: SI\n");
              break;
              case 98 : printf("Mensaje resultante: NO\n");
              break;
              case 11 : printf("Mensaje resultante: ADIOS\n");
              break;
              case 12 : printf("Mensaje resultante: HOLA\n");
              break;
              case 13 : printf("Mensaje resultante: AMIGO\n");
              break;
              case 30 : printf("Mensaje resultante: DINERO\n");
              break;
              case 31 : printf("Mensaje resultante: LIBERTAD\n");
              break;
              case 50 : printf("Mensaje resultante: YO\n");
              break;
              case 51 : printf("Mensaje resultante: TU_USTED\n");
              break;
              case 52 : printf("Mensaje resultante: EL_ELLA\n");
              break;
              case 53 : printf("Mensaje resultante: NOSOTROS\n");
              break;
              case 54 : printf("Mensaje resultante: VOSOTROS\n");
              break;
              case 55 : printf("Mensaje resultante: ELLOS_ELLAS\n");
              break;
              case 96 : printf("Mensaje resultante: INSULTO SIN ESPECIFICAR \n");
              break;
              case 97 : printf("Mensaje resultante: TAL VEZ_A VECES\n");
              break;
              case 44 : printf("Mensaje resultante: PROFESOR\n");
              break;
              case 43 : printf("Mensaje resultante: LIBRO\n");
              break;
              case 41 : printf("Mensaje resultante: TELEVISION\n");
              break;
              case 42 : printf("Mensaje resultante: PADRES\n");
              break;
              case 79 : printf("Mensaje resultante: PALABRA\n");
              break;
              case 95 : printf("Mensaje resultante: HOY_PROXIMAMENTE\n");
              break;
              case 94 : printf("Mensaje resultante: MANANA_LEJANAMENTE\n");
              break;
              case 93 : printf("Mensaje resultante: AHORA\n");
              break;
              case 46 : printf("Mensaje resultante: AMOR\n");
              break;
              case 47 : printf("Mensaje resultante: PODER\n");
              break;
              case 48 : printf("Mensaje resultante: ARRIBA\n");
              break;
              case 49 : printf("Mensaje resultante: ABAJO\n");
              break;
              case 20 : printf("Mensaje resultante: QUE\n");
              break;
              case 21 : printf("Mensaje resultante: QUIEN\n");
              break;
              case 22 : printf("Mensaje resultante: COMO\n");
              break;
              case 56 : printf("Mensaje resultante: FELIZ_FELICIDAD\n");
              break;
              case 57 : printf("Mensaje resultante: LUGAR\n");
              break;
              case 58 : printf("Mensaje resultante: Y\n");
              break;
              case 59 : printf("Mensaje resultante: 0\n");
              break;
              case 60 : printf("Mensaje resultante: SOLO\n");
              break;
              case 61 : printf("Mensaje resultante: SIEMPRE\n");
              break;
              case 6 : printf("Mensaje resultante: HACER\n");
              break;
              case 7 : printf("Mensaje resultante: IR\n");
              break;
              case 8 : printf("Mensaje resultante: VER\n");
              break;
              case 62 : printf("Mensaje resultante: NUNCA\n");
              break;
              case 701 : printf("Mensaje resultante: PRIMERO\n");
              break;
              case 702 : printf("Mensaje resultante: SEGUNDO\n");
              break;
              case 703 : printf("Mensaje resultante: TERCERO\n");
              break;
              case 63 : printf("Mensaje resultante: AYUDA_AYUDAR\n");
              break;
              case 64 : printf("Mensaje resultante: DIVEL\n");
              break;
              case 65 : printf("Mensaje resultante: INFORMACION\n");
              break;
              case 66 : printf("Mensaje resultante: PERIODICO\n");
              break;
              case 67 : printf("Mensaje resultante: INTERNET\n");
              break;
              case 68 : printf("Mensaje resultante: E-MAIL_RED SOCIAL\n");
              break;
              case 704 : printf("Mensaje resultante: CUARTO\n");
              break;
              case 705 : printf("Mensaje resultante: QUINTO\n");
              break;
              case 69 : printf("Mensaje resultante: MAS_PERO\n");
              break;
              case 70 : printf("Mensaje resultante: NUMERO\n");
              break;
              case 71 : {printf("INFONUMERO\n");
              printf("Los numeros en Zanfa se muestran con el numero 70 seguido del numero en cuestion, Divel Codigo Zanfa no puede traducir el numero así que a la hora de ingresar los datos tengalo en cuenta\n");
              }
              break;
              case 72 : {printf("INFOPROGRAMA\n");
              printf("Divel Codigo Zanfa Copyright 2011 es un programa para descodificar y codificar en Codigo Zanfa. Este programa esta integramente desarrollado en C. Mas informacion en el Manual de Usuario accesible al introducir 3 en el menu\n");
              }
              break;
              case 73 : printf("Mensaje resultante: ANIMAL\n");
              break;
              case 74 : printf("Mensaje resultante: MORIR_MUERTO\n");
              break;
              default: printf("ERROR 101--Palabra fuera de diccionario\n");
              }
  printf("Si el proceso tarda mucho o no aparece nada, Divel no ha encontrado ese archivo\n");
  } 
  
  if (a==VIVIR){
        printf("OPCION NO OPERATIVA - Revision 2012\nFin de soporte: Enero-2013\n");
  /*printf("------Introduzca sus numeros separados por ENTER(max 5)\n");
  scanf("%d",&m);
  scanf("%d",&l);
  scanf("%d",&k);
  scanf("%d",&o);
  scanf("%d",&p);
  switch(m){
            case ANIMAL : printf("73\n");
            break;
            case DIVEL : printf("64\n");
            break;
                }
 */
}
  getchar();	
  return 0;
}
getchar();
getchar();}
