/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef DIVEL_WRITE_PRIVATE_H
#define DIVEL_WRITE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.2.26"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	2
#define VER_BUILD	26
#define COMPANY_NAME	"Divel"
#define FILE_VERSION	"1.2.2"
#define FILE_DESCRIPTION	"Procesador de textos simple"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"(C) Adrián Arroyo Calle"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Divel Write"
#define PRODUCT_VERSION	"1.2.2"

#endif /*DIVEL_WRITE_PRIVATE_H*/
