/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef VISUAL_DIVEL_ENCRYPTADOR_PRIVATE_H
#define VISUAL_DIVEL_ENCRYPTADOR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.3.2.2"
#define VER_MAJOR	2
#define VER_MINOR	3
#define VER_RELEASE	2
#define VER_BUILD	2
#define COMPANY_NAME	"Divel"
#define FILE_VERSION	"Visual Divel Encryptador"
#define FILE_DESCRIPTION	"Encriptador de archivos de Divel"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"(C) Adrián Arroyo Calle"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Divel Encryptador"
#define PRODUCT_NAME	"Divel Encryptador"
#define PRODUCT_VERSION	"2.3.2"

#endif /*VISUAL_DIVEL_ENCRYPTADOR_PRIVATE_H*/
